openapi: 3.0.1
info:
  title: Fietsenwinkel
  description: |-
    Dit is een model voor registratie van inventaris en betrokken producenten en klanten van fietsenwinkels.
    Dit model heeft alleen tot doel de aard en toepassing van constructies te illustreren, en is opgezet als een UML realisatie van de in MIM besproken modelelementen.
    Het model staat bekend als IMFW.
    Het model is ontwikkeld onder toezicht van de IFO: Internationale Fietsenwinkels Organisatie.
    Dit model is opgezet conform [MIM 1.2]().
  version: 1.0.0
paths: {}
components:
  schemas:
    GeografischeLocatie:
      type: object
      description: De locatie van een aan het aardoppervlak geboden object.
      nullable: true
      anyOf:
      - $ref: https://armatiek.github.io/imvertor-openapi-generator/examples/openapi_exploded_yaml/GM_Point.yaml#/components/schemas/GM_Point
      - $ref: https://armatiek.github.io/imvertor-openapi-generator/examples/openapi_exploded_yaml/GM_Polygon.yaml#/components/schemas/GM_Polygon
