openapi: 3.0.1
info:
  title: Fietsenwinkel
  description: |-
    Dit is een model voor registratie van inventaris en betrokken producenten en klanten van fietsenwinkels.
    Dit model heeft alleen tot doel de aard en toepassing van constructies te illustreren, en is opgezet als een UML realisatie van de in MIM besproken modelelementen.
    Het model staat bekend als IMFW.
    Het model is ontwikkeld onder toezicht van de IFO: Internationale Fietsenwinkels Organisatie.
    Dit model is opgezet conform [MIM 1.2]().
  version: 1.0.0
paths: {}
components:
  schemas:
    Leverancier:
      required:
      - kvk nummer
      - naam
      - postadres
      - url
      type: object
      properties:
        url:
          minLength: 1
          type: string
          description: URL-referentie naar de resource waarnaar verwezen wordt
          format: uri
          readOnly: true
        naam:
          type: string
          description: De naam van het contact.
        postadres:
          $ref: https://armatiek.github.io/imvertor-openapi-generator/examples/openapi_exploded_yaml/Adres.yaml#/components/schemas/Adres
        betaling:
          type: array
          items:
            $ref: https://armatiek.github.io/imvertor-openapi-generator/examples/openapi_exploded_yaml/Betaalmiddel.yaml#/components/schemas/Betaalmiddel
        kvk nummer:
          $ref: https://armatiek.github.io/imvertor-openapi-generator/examples/openapi_exploded_yaml/KVKLijst.yaml#/components/schemas/KVKLijst
      description: Een instelling die een fietsen levert.
